[package]
name = "crypts-of-the-lost"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"
description = "Multiplayer dungeon MMO"
repository = "https://github.com/Sietse2202/crypts-of-the-lost"

[dependencies]
