[package]
name = "network"
version = "0.1.0"
edition = "2024"
description = "Crypt of the Lost networking"
license-file = "../../LICENSE"
repository = "https://github.com/Sietse2202/crypts-of-the-lost"
readme = "../../README.md"
keywords = ["xtask"]
categories = ["games"]

[dependencies]

[lints]
workspace = true
