name: Check

on:
  push:
    branches: ["*"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Check code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo binaries
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-tools-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-tools-${{ runner.os }}-

      - name: Install tools
        run: |
          cargo install typos-cli taplo-cli --locked --force

      - name: Run checks
        id: check
        continue-on-error: true
        run: cargo xtask check

      - name: How to fix failures
        if: steps.check.outcome == 'failure'
        run: |
          echo "The automated check failed!"
          echo "To fix, run locally:"
          echo ""
          echo "  cargo xtask check"
          echo ""
          echo "and push the resulting fixes back to this branch."
          exit 1
