name: Check

on:
  push:
    branches: ["master"]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  IS_CI: true

jobs:
  test:
    name: Check code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo binaries
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-tools-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-tools-${{ runner.os }}-

      - name: Install typos
        uses: crate-ci/typos@v1.34.0

      - name: Install taplo
        run: |
          curl -fsSL https://github.com/tamasfe/taplo/releases/latest/download/taplo-linux-x86_64.gz \ 
          | gzip -d - | install -m 755 /dev/stdin /usr/local/bin/taplo

      - name: Run checks
        id: check
        continue-on-error: true
        run: cargo xtask check

      - name: How to fix failures
        if: steps.check.outcome == 'failure'
        run: |
          echo "The automated check failed!"
          echo "To fix, run locally:"
          echo ""
          echo "  cargo xtask check"
          echo ""
          echo "and push the resulting fixes back to this branch."
          exit 1
