name: mdBook

on:
  push:
    branches: ["master"]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  IS_CI: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.14.1

      - name: Install mdbook
        run: cargo binstall mdbook --no-confirm

      - name: Build mdBook
        run: mdbook build

      - name: Remove symlinks from build output
        run: find book/ -type l -exec rm {} \;

      - name: Upload a Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book

  deploy:
    name: Deploy
    needs: build

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
